<h3 class="text-light bg-dark">Add Product</h3>
<div class="alert alert-<?php echo $success === true ? 'success' : ''; ?>">
    <?php echo $message; ?>
</div>
<?php echo $this->tag->form("products/add"); ?>
    <div class="form-group">
        <label for="productname">Product Name</label>
     <?php echo $this->tag->textField(['name' => 'productname','maxlength' => 30, 'placeholder' => 'Product Name', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
    <label for="description">Description</label>
    <?php echo $this->tag->textArea(['name' => 'description',"rows"=>"3",'maxlength' => 30, 'placeholder' => 'Add Product Description', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="tag">Tag</label>
        <?php echo $this->tag->textField(['name' => 'tag','maxlength' => 30, 'placeholder' => 'Add Product Tag', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <?php echo $this->tag->textField(['name' => 'price','maxlength' => 30, 'placeholder' => 'Price', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="stock">Stock</label>
        <?php echo $this->tag->textField(['name' => 'stock','maxlength' => 30, 'placeholder' => 'Stock', 'class' => 'form-control']); ?>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>