<h3 class="text-light bg-dark">Add Order</h3>
<div class="alert alert-<?php echo $success === true ? 'success' : ''; ?>">
    <?php echo $message; ?>
</div>
<?php echo $this->tag->form("orders/add"); ?>
    <div class="form-group">
        <label for="customername"> Customer name</label>
        <?php echo $this->tag->textField(['name' => 'customername','maxlength' => 30, 'placeholder' => 'Customer Name', 'class' => 'form-control']); ?>
    
    </div>
    <div class="form-group">
         <label for="customeraddress">Customer Address</label>
          <?php echo $this->tag->textArea(['name' => 'customeraddress',"rows"=>"3",'maxlength' => 30, 'placeholder' => 'Add Customer Address', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="zipcode">Zipcode</label>
        <?php echo $this->tag->textField(['name' => 'zipcode','maxlength' => 30, 'placeholder' => 'Zipcode', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="product">Product</label>
         <?php 
            echo Phalcon\Tag::select(
                [
                    "product",
                    Products::find(),
                    "using" => ["id", "productname"],
                    "class" => "form-control"
                ]
            ); ?>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <?php echo $this->tag->textField(['name' => 'quantity','maxlength' => 30, 'placeholder' => 'Quantity', 'class' => 'form-control']); ?>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</div> 
</form>