<h2>Create Account</h2>

<?php echo $this->tag->form("signup/register"); ?>

<div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control']); ?>
</div>

<div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField(["email", 'class' => 'form-control']); ?>
</div>

<div class="form-group">
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField(["password", 'class' => 'form-control']); ?>
</div>

<div class="form-group">
        <label for="password">Role</label>
        <?php echo $this->tag->passwordField(["role", 'class' => 'form-control']); ?>
</div>
    
<div class="form-group">
        <?php echo $this->tag->submitButton("Register"); ?>
</div>

</form>